from __future__ import annotations

from minecraft_homework_overlay_v21 import (
    ACCENT,
    ACCENT_2,
    APP_TITLE,
    BAD,
    BG,
    BORDER,
    CARD,
    CARD_2,
    CENTER,
    DEFAULT_BREAK_SECONDS,
    GOOD,
    MUTED,
    PANEL,
    TASKS_PER_BREAK,
    TEXT,
    TR,
    default_supports,
    make_child_tasks,
    normalize_input,
    t,
)


__all__ = [
    "ACCENT",
    "ACCENT_2",
    "APP_TITLE",
    "BAD",
    "BG",
    "BORDER",
    "CARD",
    "CARD_2",
    "CENTER",
    "DEFAULT_BREAK_SECONDS",
    "GOOD",
    "MUTED",
    "PANEL",
    "TASKS_PER_BREAK",
    "TEXT",
    "TR",
    "default_supports",
    "make_child_tasks",
    "normalize_input",
    "t",
]
