from __future__ import annotations

CHILD_TASKS = [{'id': 'c1_01',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 2 + 3?',
  'prompt_pl': 'Ile będzie 2 + 3?',
  'answer': '5',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_02',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 4 + 5?',
  'prompt_pl': 'Ile będzie 4 + 5?',
  'answer': '9',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_03',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 6 + 2?',
  'prompt_pl': 'Ile będzie 6 + 2?',
  'answer': '8',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_04',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 7 + 1?',
  'prompt_pl': 'Ile będzie 7 + 1?',
  'answer': '8',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_05',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 5 + 5?',
  'prompt_pl': 'Ile będzie 5 + 5?',
  'answer': '10',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_06',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 8 + 3?',
  'prompt_pl': 'Ile będzie 8 + 3?',
  'answer': '11',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_07',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 7 - 2?',
  'prompt_pl': 'Ile będzie 7 - 2?',
  'answer': '5',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_08',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 9 - 4?',
  'prompt_pl': 'Ile będzie 9 - 4?',
  'answer': '5',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_09',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 10 - 3?',
  'prompt_pl': 'Ile będzie 10 - 3?',
  'answer': '7',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_10',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 12 - 5?',
  'prompt_pl': 'Ile będzie 12 - 5?',
  'answer': '7',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_11',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 8 - 6?',
  'prompt_pl': 'Ile będzie 8 - 6?',
  'answer': '2',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_12',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: л_с',
  'prompt_pl': 'Wstaw literę: l_s',
  'answer': ['и', 'i'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c1_13',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: д_м',
  'prompt_pl': 'Wstaw literę: d_m',
  'answer': ['о', 'o'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c1_14',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: с_к',
  'prompt_pl': 'Wstaw literę: s_k',
  'answer': ['о', 'o'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c1_15',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: м_р',
  'prompt_pl': 'Wstaw literę: m_r',
  'answer': ['и', 'i'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c1_16',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Выбери слово',
  'title_pl': 'Wybierz słowo',
  'prompt_ru': 'Выбери слово МАМА',
  'prompt_pl': 'Wybierz słowo MAMA',
  'answer': 'МАМА',
  'options': ['МАК', 'КОТ', 'МАМА', 'ДОМ'],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c1_17',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Выбери ответ',
  'title_pl': 'Wybierz odpowiedź',
  'prompt_ru': 'Сколько будет 9 + 1?',
  'prompt_pl': 'Ile będzie 9 + 1?',
  'answer': '10',
  'options': ['8', '10', '11', '12'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_18',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Выбери ответ',
  'title_pl': 'Wybierz odpowiedź',
  'prompt_ru': 'Сколько будет 7 - 3?',
  'prompt_pl': 'Ile będzie 7 - 3?',
  'answer': '4',
  'options': ['3', '4', '5', '6'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c1_19',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'reading',
  'title_ru': 'Прочитай',
  'title_pl': 'Przeczytaj',
  'prompt_ru': 'Прочитай вслух: МАМА И ПАПА',
  'prompt_pl': 'Przeczytaj na głos: MAMA I TATA',
  'answer': '__read__',
  'options': [],
  'hint_type': 'reading',
  'source': 'built_in'},
 {'id': 'c1_20',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'reading',
  'title_ru': 'Прочитай',
  'title_pl': 'Przeczytaj',
  'prompt_ru': 'Прочитай вслух: ДОМ И САД',
  'prompt_pl': 'Przeczytaj na głos: DOM I SAD',
  'answer': '__read__',
  'options': [],
  'hint_type': 'reading',
  'source': 'built_in'},
 {'id': 'c1_21',
  'mode': 'child',
  'grade': 1,
  'theme': None,
  'type': 'reading',
  'title_ru': 'Прочитай',
  'title_pl': 'Przeczytaj',
  'prompt_ru': 'Прочитай вслух: У КОТА ХВОСТ',
  'prompt_pl': 'Przeczytaj na głos: KOT MA OGON',
  'answer': '__read__',
  'options': [],
  'hint_type': 'reading',
  'source': 'built_in'},
 {'id': 'c2_01',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 14 - 6?',
  'prompt_pl': 'Ile będzie 14 - 6?',
  'answer': '8',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_02',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 17 - 3?',
  'prompt_pl': 'Ile będzie 17 - 3?',
  'answer': '14',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_03',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 23 - 4?',
  'prompt_pl': 'Ile będzie 23 - 4?',
  'answer': '19',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_04',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 18 - 7?',
  'prompt_pl': 'Ile będzie 18 - 7?',
  'answer': '11',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_05',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 12 - 8?',
  'prompt_pl': 'Ile będzie 12 - 8?',
  'answer': '4',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_06',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 25 - 5?',
  'prompt_pl': 'Ile będzie 25 - 5?',
  'answer': '20',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_07',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 11 + 9?',
  'prompt_pl': 'Ile będzie 11 + 9?',
  'answer': '20',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_08',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 15 + 6?',
  'prompt_pl': 'Ile będzie 15 + 6?',
  'answer': '21',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_09',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 18 + 5?',
  'prompt_pl': 'Ile będzie 18 + 5?',
  'answer': '23',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_10',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 14 + 7?',
  'prompt_pl': 'Ile będzie 14 + 7?',
  'answer': '21',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_11',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 22 + 8?',
  'prompt_pl': 'Ile będzie 22 + 8?',
  'answer': '30',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c2_12',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 3 × 4?',
  'prompt_pl': 'Ile będzie 3 × 4?',
  'answer': '12',
  'options': ['12', '14', '11', '16'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c2_13',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 2 × 5?',
  'prompt_pl': 'Ile będzie 2 × 5?',
  'answer': '10',
  'options': ['10', '12', '9', '14'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c2_14',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 6 × 3?',
  'prompt_pl': 'Ile będzie 6 × 3?',
  'answer': '18',
  'options': ['18', '20', '17', '22'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c2_15',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 4 × 4?',
  'prompt_pl': 'Ile będzie 4 × 4?',
  'answer': '16',
  'options': ['16', '18', '15', '20'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c2_16',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: р_ка',
  'prompt_pl': 'Wstaw literę: r_ka',
  'answer': ['е', 'e', 'ę'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c2_17',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: м_ре',
  'prompt_pl': 'Wstaw literę: m_rze',
  'answer': ['о', 'o'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c2_18',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: к_са',
  'prompt_pl': 'Wstaw literę: k_sa',
  'answer': ['о', 'o'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c2_19',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: л_са',
  'prompt_pl': 'Wstaw literę: l_sa',
  'answer': ['и', 'i'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c2_20',
  'mode': 'child',
  'grade': 2,
  'theme': None,
  'type': 'reading',
  'title_ru': 'Прочитай',
  'title_pl': 'Przeczytaj',
  'prompt_ru': 'Прочитай вслух: У ЛИСЫ ПУШИСТЫЙ ХВОСТ',
  'prompt_pl': 'Przeczytaj na głos: LIS MA PUSZYSTY OGON',
  'answer': '__read__',
  'options': [],
  'hint_type': 'reading',
  'source': 'built_in'},
 {'id': 'c3_01',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 7 × 6?',
  'prompt_pl': 'Ile będzie 7 × 6?',
  'answer': '42',
  'options': [],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c3_02',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 8 × 4?',
  'prompt_pl': 'Ile będzie 8 × 4?',
  'answer': '32',
  'options': [],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c3_03',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 9 × 3?',
  'prompt_pl': 'Ile będzie 9 × 3?',
  'answer': '27',
  'options': [],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c3_04',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 6 × 8?',
  'prompt_pl': 'Ile będzie 6 × 8?',
  'answer': '48',
  'options': [],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c3_05',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 5 × 7?',
  'prompt_pl': 'Ile będzie 5 × 7?',
  'answer': '35',
  'options': [],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c3_06',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 4 × 9?',
  'prompt_pl': 'Ile będzie 4 × 9?',
  'answer': '36',
  'options': [],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c3_07',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 24 : 6?',
  'prompt_pl': 'Ile będzie 24 : 6?',
  'answer': '4',
  'options': ['4', '5', '6', '3'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_08',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 36 : 4?',
  'prompt_pl': 'Ile będzie 36 : 4?',
  'answer': '9',
  'options': ['9', '10', '11', '8'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_09',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 27 : 3?',
  'prompt_pl': 'Ile będzie 27 : 3?',
  'answer': '9',
  'options': ['9', '10', '11', '8'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_10',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 35 : 5?',
  'prompt_pl': 'Ile będzie 35 : 5?',
  'answer': '7',
  'options': ['7', '8', '9', '6'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_11',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 18 : 2?',
  'prompt_pl': 'Ile będzie 18 : 2?',
  'answer': '9',
  'options': ['9', '10', '11', '8'],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_12',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 125 - 25?',
  'prompt_pl': 'Ile będzie 125 - 25?',
  'answer': '100',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_13',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 300 - 50?',
  'prompt_pl': 'Ile będzie 300 - 50?',
  'answer': '250',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_14',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 240 - 30?',
  'prompt_pl': 'Ile będzie 240 - 30?',
  'answer': '210',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_15',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 450 - 50?',
  'prompt_pl': 'Ile będzie 450 - 50?',
  'answer': '400',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c3_16',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: дру_ба',
  'prompt_pl': 'Wstaw literę: przyja_ń',
  'answer': ['ж', 'z'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c3_17',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: кла_с',
  'prompt_pl': 'Wstaw literę: kla_s',
  'answer': ['с', 's'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c3_18',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: тра_а',
  'prompt_pl': 'Wstaw literę: tra_a',
  'answer': ['в', 'w'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c3_19',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'input',
  'title_ru': 'Вставь букву',
  'title_pl': 'Wstaw literę',
  'prompt_ru': 'Вставь букву: бе_ег',
  'prompt_pl': 'Wstaw literę: brz_g',
  'answer': ['р', 'e'],
  'options': [],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c3_20',
  'mode': 'child',
  'grade': 3,
  'theme': None,
  'type': 'reading',
  'title_ru': 'Прочитай',
  'title_pl': 'Przeczytaj',
  'prompt_ru': 'Прочитай вслух: ЗИМОЙ ПАДАЕТ БЕЛЫЙ СНЕГ',
  'prompt_pl': 'Przeczytaj na głos: ZIMĄ PADA BIAŁY ŚNIEG',
  'answer': '__read__',
  'options': [],
  'hint_type': 'reading',
  'source': 'built_in'},
 {'id': 'c4_01',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 8 × 7?',
  'prompt_pl': 'Ile będzie 8 × 7?',
  'answer': '56',
  'options': ['56', '58', '53', '61'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c4_02',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 9 × 8?',
  'prompt_pl': 'Ile będzie 9 × 8?',
  'answer': '72',
  'options': ['72', '74', '69', '77'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c4_03',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 12 × 6?',
  'prompt_pl': 'Ile będzie 12 × 6?',
  'answer': '72',
  'options': ['72', '74', '69', '77'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c4_04',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 11 × 7?',
  'prompt_pl': 'Ile będzie 11 × 7?',
  'answer': '77',
  'options': ['77', '79', '74', '82'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c4_05',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 15 × 4?',
  'prompt_pl': 'Ile będzie 15 × 4?',
  'answer': '60',
  'options': ['60', '62', '57', '65'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c4_06',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Умножение',
  'title_pl': 'Mnożenie',
  'prompt_ru': 'Сколько будет 14 × 5?',
  'prompt_pl': 'Ile będzie 14 × 5?',
  'answer': '70',
  'options': ['70', '72', '67', '75'],
  'hint_type': 'multiplication',
  'source': 'built_in'},
 {'id': 'c4_07',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 144 : 12?',
  'prompt_pl': 'Ile będzie 144 : 12?',
  'answer': '12',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_08',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 180 : 9?',
  'prompt_pl': 'Ile będzie 180 : 9?',
  'answer': '20',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_09',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 96 : 8?',
  'prompt_pl': 'Ile będzie 96 : 8?',
  'answer': '12',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_10',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 200 : 5?',
  'prompt_pl': 'Ile będzie 200 : 5?',
  'answer': '40',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_11',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Деление',
  'title_pl': 'Dzielenie',
  'prompt_ru': 'Сколько будет 81 : 9?',
  'prompt_pl': 'Ile będzie 81 : 9?',
  'answer': '9',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_12',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 125 + 75?',
  'prompt_pl': 'Ile będzie 125 + 75?',
  'answer': '200',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_13',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 350 + 150?',
  'prompt_pl': 'Ile będzie 350 + 150?',
  'answer': '500',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_14',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 240 + 160?',
  'prompt_pl': 'Ile będzie 240 + 160?',
  'answer': '400',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_15',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'input',
  'title_ru': 'Сосчитай',
  'title_pl': 'Policz',
  'prompt_ru': 'Сколько будет 1000 + 250?',
  'prompt_pl': 'Ile będzie 1000 + 250?',
  'answer': '1250',
  'options': [],
  'hint_type': 'math',
  'source': 'built_in'},
 {'id': 'c4_16',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Русский',
  'title_pl': 'Rosyjski',
  'prompt_ru': 'Выбери правильное слово: дружба',
  'prompt_pl': 'Wybierz poprawne słowo',
  'answer': 'дружба',
  'options': ['дружьба', 'друшба', 'дружба', 'друщба'],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c4_17',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Русский',
  'title_pl': 'Rosyjski',
  'prompt_ru': 'Выбери правильное слово: лестница',
  'prompt_pl': 'Wybierz poprawne słowo',
  'answer': 'лестница',
  'options': ['лестница', 'лесница', 'лестнеца', 'лестниса'],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c4_18',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Русский',
  'title_pl': 'Rosyjski',
  'prompt_ru': 'Выбери правильное слово: солнце',
  'prompt_pl': 'Wybierz poprawne słowo',
  'answer': 'солнце',
  'options': ['сонце', 'солнце', 'солце', 'солънце'],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c4_19',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'choice',
  'title_ru': 'Русский',
  'title_pl': 'Rosyjski',
  'prompt_ru': 'Выбери правильное слово: чувство',
  'prompt_pl': 'Wybierz poprawne słowo',
  'answer': 'чувство',
  'options': ['чувство', 'чуство', 'чувстно', 'чувствa'],
  'hint_type': 'letters',
  'source': 'built_in'},
 {'id': 'c4_20',
  'mode': 'child',
  'grade': 4,
  'theme': None,
  'type': 'reading',
  'title_ru': 'Прочитай',
  'title_pl': 'Przeczytaj',
  'prompt_ru': 'Прочитай вслух: СОЛНЦЕ ОСВЕЩАЕТ ЗЕМЛЮ И МОРЕ',
  'prompt_pl': 'Przeczytaj na głos: SŁOŃCE OŚWIETLA ZIEMIĘ I MORZE',
  'answer': '__read__',
  'options': [],
  'hint_type': 'reading',
  'source': 'built_in'}]
